### ISSUE TITLE
Ripple Animation

### ISSUE THREAD

**Issue by gusilveiramp** [santomegonzalo/react-native-floating-action#10]
First, thank you so much for this awesome work.
This is the best FAB library for RN.
I compared it with a mastermoo/react-native-action-button and its works smoother, also appears more stable.

The only thing missing for it to be more similar to the native FAB of the android would be the Ripple effect on the Button. Is it possible to insert this?

**Comment by santomegonzalo** [comment]
Hello, @gusilveiramp why you created this Issue?

**Comment by gusilveiramp** [comment]
Sorry, I thought the ripple effect did not exist, but it was a mistake in my code. Everything is perfect. I would like to thank you, because this is undoubtedly the best FAB library for React Native.

**Comment by santomegonzalo** [comment]
@gusilveiramp thank you! let me know if you want me to mention your app on my repo to promote it.
