### ISSUE TITLE
FAB Shadow above button

### ISSUE THREAD

**Issue by piface314** [santomegonzalo/react-native-floating-action#101]
I was using this component in a test project some days ago, and the FAB looked just like the examples. However, when I started a new project yesterday, the button shadow, that should be under the button, is being rendered above it. The code for both projects is the same, just the colors are different.

Then:
![Screenshot_20190929-122254](https://user-images.githubusercontent.com/22157025/65834832-5c7a7d00-e2b5-11e9-93ae-67df3a6000b5.jpg)

    <FloatingAction
        color="#efefef" overlayColor="rgba(0,0,0,0)"
        onPressMain={() => this.scan(2000)}
        floatingIcon={<Icon color="black" name="bluetooth-searching" />}
    />

Now:
![Screenshot_20190929-122235](https://user-images.githubusercontent.com/22157025/65834833-5c7a7d00-e2b5-11e9-91b3-65e242ed723e.jpg)

    <FloatingAction
        color="#006aff" overlayColor="rgba(0,0,0,0)"
        onPressMain={() => this.scan(2000)}
        floatingIcon={<Icon color="white" name="bluetooth-searching" />}
    />

Is it a problem with React Native version? The test project used version 0.60.5, this project used 0.61.1.

**Comment by stefoid** [comment]
I have just upgraded to RN 0.61  and can confirm it breaks the button on Android, but strangely only on some screens, even though the params to the button are the same in each screen.  When it breaks, it looks like it doesnt draw the coloured circle for the button itself, only the shadow is visible.

![Screen Shot 2019-10-02 at 3 29 07 pm](https://user-images.githubusercontent.com/8017974/66020181-8fc54200-e529-11e9-8c1b-dc430b96f0b8.png)

On IOS it looks Ok

**Comment by davidcort** [comment]
I had this problem too.
The solution was update to:  "react-native": "0.61.2"

Lucky !!  :)

**Comment by stefoid** [comment]
cheers, David.

**Comment by santomegonzalo** [comment]
Thanks @davidcort as you mentioned, the problem was React... updating to `0.61.2` will fix it
