### ISSUE TITLE
Property 'buttonSize' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FloatingAction> & Readonly<IFloatingActionProps> & Readonly<{ children?: ReactNode; }>

### ISSUE THREAD

**Issue by soorajc** [santomegonzalo/react-native-floating-action#104]
The buttonSize props is missing in the IFloatingActionProps. 

While using the  Floating Action component with TypeScript it throws the error "buttonSize property does not exist"

Kindly include buttonSize in iFlotingActionProps.

**Comment by santomegonzalo** [comment]
fixed on version `1.20.0`. Thanks @peterkuiper !
