### ISSUE TITLE
Floating button is hiding behind flatlist and also action button has a shadow .

### ISSUE THREAD

**Issue by rahulnainwal107** [santomegonzalo/react-native-floating-action#105]
I am facing an issue with this library when using it with flatlist, floating button is hiding behind flatlist items and also button has shadow from left, right and top.have a look on that two screens screens:

![Screenshot_2019-11-08-11-55-54-044_com cloudarchiveapp](https://user-images.githubusercontent.com/36499090/68455095-79915c80-0220-11ea-809f-2f78eadd508e.png
![Screenshot_2019-11-08-11-56-22-626_com cloudarchiveapp](https://user-images.githubusercontent.com/36499090/68455130-9037b380-0220-11ea-9b9c-95508c3c150d.png)
)

**Comment by santomegonzalo** [comment]
This could be because on how you are adding the button. I need more information about how are you using the flat list with the button.

**Comment by RahulNainwal** [comment]
I have added this like : 

import React, { useState } from 'react';
import { FlatList, Alert,View } from 'react-native';
import { FloatingAction } from "react-native-floating-action";

`<View style={{flex:1}}>`
`<FlatList`
`data={data}`
`keyExtractor={keyExtractor}`
`renderItem={renderItem}`
`/>`
`<FloatingAction`
`actions={actions}`
      ` showBackground={true}`
       `color={Colors.carrot_orange}`
       `onPressItem={(item) => {`
       `if (item === 'select_all') {`
       `selectAll();`
       `}`
       `else if (item === 'mapping_object') {`
       `Alert.alert('Mapping Object');`
       `}`
       `else if (item === 'run_process') {`
       `Alert.alert('Run Process');`
      ` }`
       `else {`
       `Alert.alert('Refresh');`
       `}`
      `}}`
      `/>`
`</View>`

**Comment by Dutt23** [comment]
Same issue. 
I've put it inside a container , without any styling.
Works fine in IOS though.

**Comment by Dutt23** [comment]
Adding a backgrounf color in sizeStyle , on line 412 , in file FloatingAction.js. Does fix the issue.

**Comment by marcosjoao37** [comment]
Same issue here.

I'm using like this:

```
<View style={this.pageStyle.root}>
    <View style={this.pageStyle.mainBody}>
          <TopContent />
          <ContentList />
    </View>
    <FloatingAction />
</View>
```
Where the `<ContentList />` contains the `<FlatList />`.

**Comment by marcosjoao37** [comment]
> Same issue here.
> 
> I'm using like this:
> 
> ```
> <View style={this.pageStyle.root}>
>     <View style={this.pageStyle.mainBody}>
>           <TopContent />
>           <ContentList />
>     </View>
>     <FloatingAction />
> </View>
> ```
> 
> Where the `<ContentList />` contains the `<FlatList />`.
> Also, I had suppressed the `<FloatingAction />`'s options here.

So I just added a `zIndex: 0` on `pageStyle.mainBody` style and fixed it.

**Comment by nihp** [comment]
I need to set the button as a color and floating buttons as an another color with an image. Can I able to make that different for that Icon

**Comment by iamshhree** [comment]
make the <FloatingAction> the last node in your <View> . That works for me perfectly.!!
