### ISSUE TITLE
Unable to tap the button when position is absolute [Android]

### ISSUE THREAD

**Issue by leonsoh** [santomegonzalo/react-native-floating-action#106]
Hello, first of all thank you for this library 👍   

I had encountered a problem when wrapping a view with position `absolute`. The action button doesn't seem to trigger any click.  

I am still fairly new to React Native, so if I had misunderstood any usage parts please let me know, thanks! 

**This issue is on Android. iOS is working fine.**

Example code:
```
    <View style={ {position: 'absolute', top: 80, left: 80} }>
      <FloatingAction />
    </View>
```

React Native: `0.60.5`
Device: Tried physical/emulator,  Pixel XL API 29

**Comment by gauravroy1995** [comment]
same here, even without aboslute, button is not clickable, infact the below compoent is getting clicked. and tried with zindex too , but no use.

**Comment by leonsoh** [comment]
Okay, I tried implement custom fab from scratch and encountered the same issue. I managed to solve it by wrapping the `TouchableOpacity` onto another `View` with `width` and `height` so that it will be clickable. This solution is to resolve Android's touchable issue.

**Comment by CryceTruly** [comment]
I had a similar issue, the problem was that I had a TouchableOpacity as the direct Parent.i removed that, and things are working
