### ISSUE TITLE
distanceToEdge is not working for different pages.

### ISSUE THREAD

**Issue by sankar9659** [santomegonzalo/react-native-floating-action#107]
I have used distanceToEdge props, to show the icon in every page in every  position, but it's not working, I put that in main APP page
Here is my code,

floatingIconEdge = () => {
		// floating icon showing edges for different screens
		const { currentScreen } = this.state
		Reactotron.log({ currentScreen: currentScreen });
		switch (currentScreen) {
			case 'ShopScreen':
				return { vertical: 0, horizontal: 0 }
			case 'StoreHome':
				return { vertical: 10, horizontal: 10 }
			default:
				return { vertical: 40, horizontal: 40 }
		}
	}
<FloatingAction
							actions={actions}
							floatingIcon={<Icon name={'ios-help-circle-outline'} style={{ fontSize: 30, color: '#ffffff' }} />}
							onPressItem={name => {
								Reactotron.error({ name });
								NavigationService.navigate('ChatRoom')
							}}
							distanceToEdge={this.floatingIconEdge()}
							color={'#2cb673'}
							visible={this.floatingIconVisible()}
						/>

**Comment by santomegonzalo** [comment]
I need more information because react native Views are not like HTML and depends on which device are you using (android or ios).

**Comment by nowarzz** [comment]
I am also unable to use distanceToEdge with object { horizontal : Number, vertical: Number } but was able to do with Number...

the error I got is: 
"Error while updating property 'paddingLeft' in shadow node of type: RCTView

Unknown value: [object Object]8

meanwhile 8 is the default value of padding

**Comment by nowarzz** [comment]
Device: Android.
