### ISSUE TITLE
Do you have plan to support accept a component for icon?

### ISSUE THREAD

**Issue by Harryki** [santomegonzalo/react-native-floating-action#11]
As i understand so far, only image files are supported for icon. do you have plan to support any component like Icon (react-native-element)?

**Comment by faogustavo** [comment]
Already have :) #5

**Comment by santomegonzalo** [comment]
@Harryki as you can see in the doc https://github.com/santomegonzalo/react-native-floating-action#configuration you can use wherever ReactElement that you want. Just use `floatingIcon`.

**Comment by santomegonzalo** [comment]
Hello @Harryki ... I created a new app on expo to show different examples of what you can do with this component... https://expo.io/@santomegonzalo/ReactNativeFloatingAction-Expo
