### ISSUE TITLE
Overwrite position for main button

### ISSUE THREAD

**Issue by khrizt** [santomegonzalo/react-native-floating-action#12]
I'd be great to be able to overwrite the bottom, for all positions, and left / right values for right and left positioning using props. Do you think it's a good idea? I can do a PR if you want.

**Comment by santomegonzalo** [comment]
Hello @khrizt ! sorry for the delay.

That is a good idea... and in my opinion will not be hard to do it... you are more than welcome to do it, and please if you have any question just let me know.

**Comment by khrizt** [comment]
Take a look at this PR https://github.com/santomegonzalo/react-native-floating-action/pull/13 I can change the implementation if you prefer another one.

**Comment by santomegonzalo** [comment]
thanks @khrizt I will take a look!

**Comment by santomegonzalo** [comment]
@khrizt I just merged your PR. thank you very much for the update! please if you are using this plugin on a public app let me know so I could promote it in the README.

**Comment by khrizt** [comment]
Thanks man!! 

I'm using it but it's not public yet. I'll get in touch when it's released.

**Comment by khrizt** [comment]
Sorry man, I introduced a bug with the distanceToEdge parameter. The FloatingActionItem's were not aligned to the main button when the parameter was used. I've created a new pull request to fix that. https://github.com/santomegonzalo/react-native-floating-action/pull/15
