### ISSUE TITLE
How can I solve this warning? Animated: useNativeDriver was not specified

### ISSUE THREAD

**Issue by HoWWWWWhy** [santomegonzalo/react-native-floating-action#136]
I have this warning. Please help me.
 
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

Is it possible to solve this problem?

Thank you.

**Comment by harshdvaid24** [comment]
facing same issue dude.

**Comment by jpouabou** [comment]
Same issue.
