### ISSUE TITLE
[Request] Single action (no menu)

### ISSUE THREAD

**Issue by arronhunt** [santomegonzalo/react-native-floating-action#16]
It would be great if you could use the button itself as a single action, with it's own icon. For things like "Save", etc.

**Comment by santomegonzalo** [comment]
Hi, @arronhunt that feature already exists. Please try the following...

```javascript
        <FloatingAction
          overrideWithAction
          actions={actions}
          visible={actionButtonVisible}
          onPressItem={
            (name) => {
              Alert.alert('Icon pressed', `the icon ${name} was pressed`);
            }
          }
        />
```

In the documentation, you could find that **overrideWithAction** works to replace the main action with the first action inside the list of actions. That will fix your case.

Please let me know if there is something else.

**Comment by arronhunt** [comment]
@santomegonzalo Thanks! I was a little confused by the documentation but that works great.

**Comment by santomegonzalo** [comment]
@arronhunt no problem, I will update the documentation and I will create examples on **expo** so that will help everybody.

**Comment by pecabum** [comment]
This thing doesn't work like that... is there any update ?

**Comment by qasimalbaqali** [comment]
Not working with me as well.

**Comment by santomegonzalo** [comment]
hi @pecabum and @qasimalbaqali did you test the example on expo?
