### ISSUE TITLE
visible prop not working in initial render - always set to `true`

### ISSUE THREAD

**Issue by Norfeldt** [santomegonzalo/react-native-floating-action#19]
This code does not work as expected. The button is always visible in the first render. 

Works as expected when updating the state and making the someArray an empty array.

         ...
          <FloatingAction
            overrideWithAction
            actions={FABactions}
            visible={this.state.someArray.length > 0}
            onPressItem={() => console.log('FAB pressed')}
            buttonColor="#6699CC"
          />
     

trying to set the `visible` prop to `false` also display the FAB...

This code below works as expected in first render. (but lacks the awesome entrance animation)

```
{this.state.someArray.length > 0 && (
          <FloatingAction
            overrideWithAction
            actions={FABactions}
            onPressItem={() => console.log('FAB pressed')}
            buttonColor="#6699CC"
          />
        )
}
```

**Comment by santomegonzalo** [comment]
Hello @Norfeldt I will take a look today... Thanks!

**Comment by santomegonzalo** [comment]
Hi @Norfeldt I just pushed a new version `1.6.0` with a fix for your bug. You were right and I had a bug in my code. **Expo** was updated with an example.
