### ISSUE TITLE
checkPropTypes

### ISSUE THREAD

**Issue by brendanmanning** [santomegonzalo/react-native-floating-action#2]
Will be removed by React 16

My package.json dependencies
`"dependencies":` {
    "expo": "^18.0.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-floating-action": "^1.1.0",
    "react-navigation": "^1.0.0-beta.11"
  }
`

See below
![img_3225](https://user-images.githubusercontent.com/14865682/28188183-41fdace2-67ef-11e7-8c07-7ca02f777f33.PNG)
![img_3226](https://user-images.githubusercontent.com/14865682/28188184-42009b3c-67ef-11e7-89b5-8204f1e42368.PNG)

**Comment by santomegonzalo** [comment]
hi @brendanmanning this is a problem from react animations... as soon as they fixed it you will not see this warning anymore because my package is using your local react-native. I will tell you here when they release a new version.

**Comment by santomegonzalo** [comment]
@brendanmanning I just upgrade my `example` app to the latest version of react **0.46.3** and the yellow box is not there anymore... So I recommend you to upgrade the version. Thanks!
