### ISSUE TITLE
Interest in contributing with this project

### ISSUE THREAD

**Issue by araujobarret** [santomegonzalo/react-native-floating-action#26]
Hello Gonzalo, how are you?

I am using this library and I have to thank you, this is an awesome library, the best that I found for React Native.

I am currently modifying it to use on my project, and I was thinking which those mods can be useful to this project.

Because of the size of lodash library, I am removing it from the lib, and I am enabling the some styles of FloatingActionItems, like width, height, padding, margin, even in the centered Items.
And of course, I am respecting the patterns keeping it like a high order component itself.

If this sounds interesting to your project, I would be glad to contribute with this project.

Ps.: these changes aren't done yet 
Cheers.

**Comment by santomegonzalo** [comment]
Hello Araujo, thanks for your words! I really appreciate it... and of course, the idea of this package was to build just a simple and performance control... I would love to get more help with new ideas because I build this package to use it for my current projects.

I will invite you to be part of this project!

**Comment by araujobarret** [comment]
Hello again @santomegonzalo 

I did some modification on the component removing the dependency of lodash(I only checked null text values and created a bubble sort method for actions sort, I only saw these 2 kind of dependencies of lodash).

This is what I did:

![capture](https://user-images.githubusercontent.com/15792853/35590863-3ebcd4d8-05ef-11e8-99dc-4ba6a6e6d3ae.PNG)

What do you think? Is this something useful to add to the project too?

Ps: this print is missing the icon in the rectangle view

**Comment by santomegonzalo** [comment]
that is really nice... yes more flexibility always is better... but always if the documentation is clear... that was the idea behind this library... make a clear documentation with examples on Expo and then make a simple **interface**
