### ISSUE TITLE
when i scroll down listview,how to hide this component

### ISSUE THREAD

**Issue by est7** [santomegonzalo/react-native-floating-action#3]

**Comment by santomegonzalo** [comment]
Hi @est7 I will have that feature done this week, probably tomorrow will be online... I will let you know as soon as it's available!

**Comment by est7** [comment]
@santomegonzalo thanks

**Comment by santomegonzalo** [comment]
Hi @est7 I just pushed a new version where now you can set `visible: false` and that will hide the component... but now you need to connect it to the `FlatList`... I updated the example and there you can see how that works... 

Here is a gif showing the functionality: https://user-images.githubusercontent.com/2914973/29421294-e74df51c-8374-11e7-96ca-62675075f8e8.gif

Here is the example: https://github.com/santomegonzalo/react-native-floating-action/blob/master/example/FloatingAction/index.ios.js

If this works please close the issue :) and I would like to know if your app will go public so I could add your app on my repository.

Best

**Comment by stonecold123** [comment]
@santomegonzalo 
That example has been removed. I couldn't find a related example in expo. Do you use `onMomentumScrollEnd` and `onScroll` from the Flatlist to do the hiding and showing?

**Comment by santomegonzalo** [comment]
hello @stonecold123 I will be adding the example soon. That example is not related to this component, that's why I decided to not include it right now

**Comment by fukemy** [comment]
hi, please update example with flatlist plz
