### ISSUE TITLE
Visible Initial False dosn't work

### ISSUE THREAD

**Issue by Hvkvn** [santomegonzalo/react-native-floating-action#32]
Is this really fixed?

          <FloatingAction
            visible={false}
            actions={actions}
            ... />
In my Case the Button is still visible.

**Comment by santomegonzalo** [comment]
Hello, @Hvkvn I'm looking into it right now.

**Comment by santomegonzalo** [comment]
@Hvkvn I'm looking into it and I found it's a bug on Android. iOS works perfect. I will keep looking or I will take another way to fix it.

I will keep you posted.

https://github.com/facebook/react-native/issues/6278

**Comment by santomegonzalo** [comment]
@Hvkvn I just deployed a new version **1.10.1** please update to that version and everything will work

![mar-26-2018 17-24-31](https://user-images.githubusercontent.com/2914973/37915861-c3d10922-311a-11e8-8197-b2c71a6294be.gif)

Please let me know if works.
.

**Comment by Hvkvn** [comment]
Thank you it works now.
