### ISSUE TITLE
Navigate to a new Screen onPressItem

### ISSUE THREAD

**Issue by Hvkvn** [santomegonzalo/react-native-floating-action#34]
I want to navigate to a new Screen when a item is pressed.
Is this possible ?

**Comment by Hvkvn** [comment]
Could you send an example which works?

**Comment by santomegonzalo** [comment]
@Hvkvn please for this questions follow https://reactnavigation.org/docs/navigating.html#navigating-to-a-new-screen or you could take a look at my expo example to see how I navigate to the next screen.

My intention with my examples is to show how the component works and not how ReactNavigation works.

**Comment by Hvkvn** [comment]
My Problem is that i want to navigate to a specific Screen dependent on which Action is clicked.
For example Somthing like this: 
           <FloatingAction
            actions={actions}
            onPressItem={
              (name) => {
                if (name == 'bt_homeScreen') {
                  this.props.navigation.navigate('HomeScreen')
                } if (name == 'bt_infoScreen') {
                  this.props.navigation.navigate('InfoScreen')
                }
              }
            }
          />

I have seen your examples, but there is nothing suitable for my problem

**Comment by santomegonzalo** [comment]
@Hvkvn what you are showing me its correct... that is not working?

**Comment by Hvkvn** [comment]
That example is not working. Is it maybe a bug?

**Comment by santomegonzalo** [comment]
@Hvkvn I need more information. I'm using this plugin on different apps and works. If you could do an example of what you are doing will be nice so I could look it deeper.

**Comment by Hvkvn** [comment]
Sorry it was my mistake. The navigation path is named different than i thought.

**Comment by santomegonzalo** [comment]
great! let me know if there is something else @Hvkvn !

Best

**Comment by ansarikhurshid786** [comment]
Now it is working fine.
