### ISSUE TITLE
Wrong ripple color

### ISSUE THREAD

**Issue by zwerg44** [santomegonzalo/react-native-floating-action#44]
**version:** 1.10.1

Looks like `shadeColor` function supports only `#00879d` color format.

It causes weird ripple effect with wrong color in case of FloatingAction color is set in other formats. 
It would be nice to have support of other color formats for example: `rgba(0,135,157,1)` or `#888`.
Or some note about it in readme at FloatingAction's color prop.

`shadeColor('rgba(0,135,157,1)', -30);`
`// returns that color` `#ff0700` 

I suggest to use this lib for color shading:
https://github.com/Qix-/color

**Comment by santomegonzalo** [comment]
Hello @zwerg44 I will take a look today and fix it... thanks for the issue

**Comment by mohamdaoui** [comment]
Any news on this one? seems to still be an issue on `1.14.2`

**Comment by santomegonzalo** [comment]
Sorry for the long delay... @zwerg44 @mohamdaoui  I just pushed a new version with a fix for this color thing. https://github.com/santomegonzalo/react-native-floating-action/pull/84

**Version: 1.17.0**
