### ISSUE TITLE
uncompiled PNG file passed as argument. Must be compiled first into .flat file.

### ISSUE THREAD

**Issue by hecontreraso** [santomegonzalo/react-native-floating-action#45]
Getting this error after I updated to gradle 3

`
miapp/android/app/build/intermediates/res/merged/release/drawable-xhdpi/node_modules_reactnativefloatingaction_images_add.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays
`

**Comment by santomegonzalo** [comment]
This is weird... today i will uodate to the latest react native and i will check whats going on

**Comment by n1ru4l** [comment]
https://github.com/facebook/react-native/issues/16906#issuecomment-365790350

**Comment by santomegonzalo** [comment]
hi @hecontreraso . I just deployed a new version `1.12.1` fixing this error. Basically I replaced the png file for a simple react component. Now for us works perfectly. 

Thanks for the support @n1ru4l
