### ISSUE TITLE
floating button not shown on iOS when the keyboard is displayed

### ISSUE THREAD

**Issue by hashmatmuqbil** [santomegonzalo/react-native-floating-action#49]
Hi,
Floating button is getting hidden by keyboard on iOS when the keyboard is on, but it works fine on Android

**Comment by santomegonzalo** [comment]
Hi @hashmatmuqbil , I never used this case before, but its a normal problem with iOS because depends on how the `View` is rendered... Let me take a look to see if it's possible to set this feature to follow the keyboard.

**Comment by santomegonzalo** [comment]
Another thing that came to my mind, iOS will show the keyboard when we are doing focus on a Text. but as soon as you will try to click on something else (like floating action) the keyboard will disappear... But let me take a look.

**Comment by santomegonzalo** [comment]
Hello @hashmatmuqbil ... your request was awesome. I never thought on this. Please get the latest version `1.12.0`. Here are the release notes: https://github.com/santomegonzalo/react-native-floating-action/releases/tag/v1.12.0

Thanks again for the support.

If you like I could promote your app on my repository.
