### ISSUE TITLE
Fixed floating action button between top tab change. 

### ISSUE THREAD

**Issue by DimitrisTzimikas** [santomegonzalo/react-native-floating-action#62]
Is there a way to have the button fixed on bottom right while i switch between top tabs? Right now i'm switching screens but the button is on every single one of them.

**Comment by msevestre** [comment]
Can you define the floating action component in the parent component (e.g. at the same level as the tabs component?)

**Comment by santomegonzalo** [comment]
Hi @DimitrisTzimikas ... as @msevestre said, the only way is to define the component in the parent because that is how React Native works...

**Comment by DimitrisTzimikas** [comment]
Thanks @msevestre & @santomegonzalo!! Sometimes the simplest things are the hardest to get... It just had to put it in the root component as you said.

**Comment by santomegonzalo** [comment]
good to heard @DimitrisTzimikas !
