### ISSUE TITLE
Action Button not showing up on Android, working fine on iOS

### ISSUE THREAD

**Issue by noumantahir** [santomegonzalo/react-native-floating-action#67]
I am using Floating Action Button version 1.13.0. It's working find on iOS but doesnt even show up on Android, I even tried changing layouts and also tried out variants of relative and absolute position but no luck...

```
          <View style={{justifyContent:'flex-end'}}>
            <FloatingAction
              ref={(component)=>{this.floatingAtionMenu=component}}
              actions={this.state.actions}
              showBackground={false}
              color={Values.Colors.COLOR_PRIMARY}
              overlayColor={Values.Colors.COLOR_PRIMARY}
              onPressItem={(name)=>{
                console.log(`Selected Fab Action: ${name}`)
              }}
              />
            </View>
```

Some information about versions I am using...

React Native

> "react-native": "0.52.0",
> "react-native-floating-action": "^1.13.0"

Android

>     compileSdkVersion   = 27
>     targetSdkVersion    = 27
>     minSdkVersion       = 16
>     buildToolsVersion   = "27.0.3"
>     supportLibVersion   = "27.0.2"
>     googlePlayServicesVersion = "15.0.1"

Some Screenshots
iOS
![simulator screen shot - iphone 6 - 2018-10-17 at 14 47 23](https://user-images.githubusercontent.com/6298342/47078082-eacc2f00-d21b-11e8-8487-a215ef775f00.png)

Android
![screenshot_1539769759](https://user-images.githubusercontent.com/6298342/47078092-f1f33d00-d21b-11e8-8c6c-dbd7195fc024.png)

**Comment by santomegonzalo** [comment]
Closing because for 2 weeks I didn't get any response
