### ISSUE TITLE
Floating Icon

### ISSUE THREAD

**Issue by VjVijey** [santomegonzalo/react-native-floating-action#68]
How we can change the **plus icon** of the Button?

**Comment by santomegonzalo** [comment]
the plus icon is not possible to change it right now if you want to have sub actions after the user press it. If you don't want that sub actions then please check this https://github.com/santomegonzalo/react-native-floating-action/blob/master/example/ReactNativeFloatingAction-Expo/screens/FloatingActionOverrideWithActionScreen.js

The problem with override the button is that I need to set an icon for close and another icon to close...  if you want this feature please be free to make it an open a PR
