### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by gusilveiramp** [santomegonzalo/react-native-floating-action#7]
Congratulations on your work and thank you very much for making it available.
I use react-native-material-bottom-navigation and the tab is superimposed on the button. How do I position him further up? I do not want him to override Tab, but rather stay a little above it.

**Comment by santomegonzalo** [comment]
Hello @gusilveiramp did you fixed the problem? I'm using **react-native-material-bottom-navigation** and I don't have any problem.

**Comment by crespoter** [comment]
@gusilveiramp I am having the same problem. Have you found a solution ?

**Comment by crespoter** [comment]
There doesnt seem to be any option to set just the vertical margin on the FloatingActionItem object. I was able to set the margin by editing the FloatingAction.js file in the library and setting marginBottom for Main Button and Actions.

**Comment by gusilveiramp** [comment]
Hi @crespoter, sorry for the super late reply.
Yeah, I solved the problem exactly like this. I modified the FloatingAction.js file according to my need and submitted it to a private repository in order to use npm install without losing the changes. You can also simply copy it to your project, eg.: put it in the components folder and use it (import it) directly from there. Good luck in your project!

**Comment by fidabhittani** [comment]
Hi I think that is a bit complicated solution.
What I did was to wrap it in a `View` then instead of using marginBottom, I used bottom
![image](https://user-images.githubusercontent.com/5584787/82617803-9e608680-9bea-11ea-88a8-36e7c4d4266d.png)
