### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by Salil999** [santomegonzalo/react-native-floating-action#73]
Is it possible to stop the rotation animation of the button when it is pressed? I just need the button itself.

**Comment by Salil999** [comment]
I temporarily fixed this by commenting out these lines in the source code:
https://github.com/santomegonzalo/react-native-floating-action/blob/master/component/FloatingAction.js#L207-L209

**Comment by santomegonzalo** [comment]
Hi @Salil999 I will work on this tonight and create an example of this.

**Comment by EstopaceMA** [comment]
hello, how's the progress in here? , I just need as well the button itself
