### ISSUE TITLE
FloatingAction button shadow

### ISSUE THREAD

**Issue by czystyl** [santomegonzalo/react-native-floating-action#79]
Even if we are providing the custom component for The Floating Button, the shadow is still visible.

![image](https://user-images.githubusercontent.com/10349378/53430148-44c0da80-39ee-11e9-9c03-8f4ba5bad1d6.png)

Code:
```
<FloatingAction
  distanceToEdge={30}
  actions={actions}
  floatingIcon={<View style={{ height: 50, width: 50, backgroundColor: 'yellow', borderRadius: 50 }} />}
  color="transparent"
  actionsPaddingTopBottom={0}
  showBackground={false}
  onOpen={this.handleOpen}
  onClose={this.handleClose}
  onPressItem={this.handlePressItem}
/>
```

**Comment by santomegonzalo** [comment]
The shadow is always there... I will add a new prop to remove that shadow if the user wants

**Comment by santomegonzalo** [comment]
Hi @czystyl I just merged and deployed a new version allowing you to change or remove the shadow... On expo you could change the new prop (I created a new screen).
If you want to hide it please follow this example: https://github.com/santomegonzalo/react-native-floating-action/blob/master/example/screens/FloatingActionShadow.js#L50

This is the PR: https://github.com/santomegonzalo/react-native-floating-action/pull/83

**Comment by nihp** [comment]
Unable to see the text if I position this to center of the screen?

Any solution for that?
