### ISSUE TITLE
Action button giving ripple drawable error on android API 19. KITKAT

### ISSUE THREAD

**Issue by prashantvv** [santomegonzalo/react-native-floating-action#8]
Hello, the floating action button is giving error in andorid  API <21. full error as follows:

Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

null

Ripple drawable is not available on android API <21
updateViewProp
    ViewManagersPropertyCache.java:95
setProperty
    ViewManagerPropertyUpdater.java:129
.
.
.

**Comment by santomegonzalo** [comment]
Hi @prashantvv I will take a look and come back to you ASAP

**Comment by santomegonzalo** [comment]
Hello @prashantvv ! I just pushed version **1.3.1** with a fix for your problem! 

Thanks for reporting this issue, and I would like to know in which app you are using my component so I could add some credits on my README.

Thanks

**Comment by prashantvv** [comment]
Hello @santomegonzalo , the app is under development, although I found the issue in android KITKAT version API 19 while testing both in emulator as well as in real device.

**Comment by santomegonzalo** [comment]
Ok perfect @prashantvv . Let me know if you found another issue!
