### ISSUE TITLE
Question on your TODO 

### ISSUE THREAD

**Issue by Louis345** [santomegonzalo/react-native-floating-action#80]
I'm interested in contributing and was wondering what you meant by crazy animations? Is there anything I can do to help this repo? 

Thanks.

**Comment by santomegonzalo** [comment]
Hi @Louis345 !!! you are more than welcome to help me with new features... I was thinking something like animations from outside the screen or something like that... or something like the developers could define their animations... maybe trying a new library like https://github.com/kmagiera/react-native-reanimated

**Comment by santomegonzalo** [comment]
Closing because there was no more activity.
