### ISSUE TITLE
How to reset isActive state ?

### ISSUE THREAD

**Issue by getavinashm** [santomegonzalo/react-native-floating-action#85]
Hi,
  I am trying to redirect to another screen in certain conditions when tapping on main button. This happens, however when navigating back to the screen is showing the inactive backdrop. User has to tap on the screen to make it active. Until then the state remained at false. How do I set the state to false programatically so that screen remains active after I navigate away ?

**Comment by santomegonzalo** [comment]
Hi @getavinashm the best way to do it is the following

```
<FloatingAction
    ref={ref => {
        this.action = ref;
    }}
    // more props...
/>
```

and then when you press the action and you navigate you could call the following

```
this.action.animateButton();
```

and that will hide it if the actions are visible...

Let me know if that works

**Comment by santomegonzalo** [comment]
Closing because there was no more activity.

**Comment by aniruddhashevle** [comment]
@santomegonzalo :  instead of `this.action.animateButton();` you mentioned above, `this.action.reset();` would be the best! @getavinashm : Please note this.
