### ISSUE TITLE
latest version seems broken

### ISSUE THREAD

**Issue by tachtevrenidis** [santomegonzalo/react-native-floating-action#97]
error ▶︎ Failed to compile.
error ▶︎ [ '/Users/vsts/agent/2.155.1/work/1/s/common/temp/node_modules/.onedrive.pkgs.visualstudio.com/react-native-floating-action/1.19.0/react-native@0.60.5+react@16.8.6/node_modules/react-native-floating-action/src/FloatingAction.js\nModule build failed (from /Users/vsts/agent/2.155.1/work/1/s/common/temp/node_modules/.onedrive.pkgs.visualstudio.com/babel-loader/8.0.6/webpack@4.39.3/node_modules/babel-loader/lib/index.js):\nSyntaxError: /Users/vsts/agent/2.155.1/work/1/s/common/temp/node_modules/.onedrive.pkgs.visualstudio.com/react-native-floating-action/1.19.0/react-native@0.60.5+react@16.8.6/node_modules/react-native-floating-action/src/FloatingAction.js: Unexpected token, expected "," (134:10)\n\n  132 |           buttonSize +\n  133 |           this.distanceToVerticalEdge\n> 134 |           actionsPaddingTopBottom +\n      |           ^\n  135 |           height -\n  136 |           (isIphoneX() ? 40 : 0),\n  137 |         duration:

**Comment by crobinson42** [comment]
A simple (dumb) overlooked mistake was published. @santomegonzalo 

This is where a precommit hook to run eslint will save everyone a headache 😞 

<img width="268" alt="Screenshot 2019-08-30 13 36 42" src="https://user-images.githubusercontent.com/5973579/64049908-45683400-cb2b-11e9-9216-d1dd1f17bab6.png">

**Comment by santomegonzalo** [comment]
fixing it now

**Comment by santomegonzalo** [comment]
I just pushed a fix for this error. Sorry about that I will work on the prehooks next week.

**Comment by antonkulyk** [comment]
My fault, sorry for that 😞
